# Generated by Django 4.0.2 on 2022-02-23 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBanIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('attempts', models.IntegerField(default=0, verbose_name='Неудачных попыток')),
                ('time_unblock', models.DateTimeField(blank=True, verbose_name='Время разблокировки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус блокировки')),
            ],
            options={
                'verbose_name': 'Temporarily banned IPs',
                'verbose_name_plural': 'Temporarily banned IPs',
                'db_table': 'TemporaryBanIp',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('icon', models.ImageField(default='images/user_avatars/user-img.png', null=True, upload_to='images/user_avatars/', verbose_name='User Avatar')),
                ('lang', models.CharField(default='en', max_length=100, null=True, verbose_name='Language')),
            ],
        ),
    ]
