# Generated by Django 4.0.2 on 2022-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Django Project', max_length=100, verbose_name='Site name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/site settings/logo/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/site settings/favicon/', verbose_name='Fav Icon')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'main_site_settings',
            },
        ),
    ]
