# Generated by Django 4.0.2 on 2022-03-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_worktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktable',
            name='is_run',
            field=models.BooleanField(default=False, verbose_name='is_run'),
            preserve_default=False,
        ),
    ]
